config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
                controllers: { registrations: "devise/registrations"}

  root :to => 'static_pages#home'

  get "/static_pages/:page" => "static_pages#show"

  resources :posts do
    resources :comments
  end

  resources :profiles

  resources :users do
    resources :beers
  end

  resources :beers do
    resources :conversations
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :messages, only: [:new, :create]

  resources :conversations do
   member do
     post :reply
     post :trash
     post :untrash
   end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @beer = Beer.find(params[:beer_id])
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @beer = Beer.find_by(:name => conversation.subject)
    @receipts = conversation.receipts_for(current_user).order(created_at: :asc)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
   current_user.reply_to_conversation(conversation, message_params[:body])
   flash[:notice] = "Your reply message was successfully sent!"
   redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

 private

 def conversation_params
   params.require(:conversation).permit(:subject, :body, recipients:[])
 end

 def message_params
   params.require(:message).permit(:body, :subject, recipients:[])
 end
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(conversation.originator.profile.avatar.url(:thumb)) %>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      Conversation starter: <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    Most recent message: <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View Conversation", conversation_path(conversation)  %>
    <hr>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <h4> From: <%=current_user.name %></h4>
    <h4> To: <%= @beer.user.name %></h4>
    <h4> Subject: <%= @beer.name %></h4>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>
    <%= f.hidden_field :recipients, :multiple => true, :value => [@beer.user.id] %>
    <%= f.hidden_field :subject, :value => @beer.name %>
    <h4><%= f.submit "Send Message", class: "btn btn-lg button-tan" %></h4>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
  <% message = receipt.message %>
  <div class="media">
    <div class="media-left">
      <%= link_to image_tag(message.sender.profile.avatar.url(:thumb)) %>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= message.sender.name %><br>
        <small><b>Subject: </b><%= message.subject %></small><br>
        <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
      </h4>
      <%= message.body %>
    </div>
  </div>
<% end %>

app/views/conversations/new.html.erb
<div class="container push-down">
  <div class="col-sm-12 bottom">
    <%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container">
  <h4 class="center italic push-down"> ~ This is a private conversation between <%= conversation.originator.name %> and <%= @beer.user.name %> ~</h4>
  <div class="row push-down-lite bottom">
    <div class="col-md-4">
      <%= render :partial => '/beers/small_beer', locals: {:@beer => @beer, :@user => current_user } %>
      <% if conversation.is_trashed?(current_user) %>
        <h4 class="indent"><%= link_to 'Un-archive', untrash_conversation_path(conversation), class: 'btn btn-lg btn-block button-tan', method: :post %></h4>
      <% else %>
        <h4 class="indent"><%= link_to 'Archive conversation', trash_conversation_path(conversation), class: 'btn btn-lg btn-block button-tan', method: :post,
                      data: {confirm: 'Are you sure?'} %></h4>
      <% end %>
        <h4 class="indent"><%= link_to 'Back to Inbox', mailbox_inbox_path, class: 'btn btn-lg btn-block button-teal' %></h4>
    </div>

    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render partial: 'messages' %>
        </div>
        <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Add to the conversation!", rows: 4, class: "form-control" %>
            </div>
            <h4><%= f.submit "Send", class: 'btn btn-lg button-teal pull-left' %></h4>
        <% end %>
        <div class="clearfix"></div>
      </div>
      </div>
    </div>
  </div>
</div>