config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
                controllers: { registrations: "devise/registrations"}

  root :to => 'static_pages#home'

  get "/static_pages/:page" => "static_pages#show"

  resources :posts do
    resources :comments
  end

  resources :profiles

  resources :users do
    resources :beers
  end

  resources :beers do
    resources :conversations
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :messages, only: [:new, :create]

  resources :conversations do
   member do
     post :reply
     post :trash
     post :untrash
   end
  end
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :user
  belongs_to :style
  validates :name, :container_type, :description, :brew_date, :user_id, :style_id, :presence => true
  default_scope { order('created_at DESC') }
  scope :style_id, -> (style_id) { where style_id: style_id }
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :require_permission, only: [ :edit, :destroy ]

  def index
    @beers = Beer.where(nil)
    @recent_beers = Beer.first(4)
    @styled_beers = Beer.style_id(params[:style_id]) if params[:style_id].present?
    @near_beers = []
    @near_profiles = []
    @near_profiles = Profile.where("neighborhood = ?", params[:neighborhood]) if params[:neighborhood].present?
    if @near_profiles.any?
      @near_profiles.each do |profile|
        if profile.user.beers.any?
          profile.user.beers.each do |beer|
          @near_beers << beer
          end
        end
      end
    end
    @hash = Gmaps4rails.build_markers(@beers) do |beer, marker|
      marker.lat beer.user.profile.latitude
      marker.lng beer.user.profile.longitude
    end
  end

  def new
    @user = User.find(params[:user_id])
    @beer = @user.beers.new
    @styles = Style.all
  end

  def create
    @user = User.find(params[:user_id])
    @beer = @user.beers.new(beer_params)
    @styles = Style.all
    if @beer.save
      respond_to do |format|
        format.html {redirect_to profile_path(@user)}
        format.js
      end
    else
      flash[:alert] = "Oops, something went wrong!"
      redirect_to profile_path(@user)
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @beer = @user.beers.find(params[:id])
    @styles = Style.all
  end

  def update
    @user = User.find(params[:user_id])
    @beer = @user.beers.find(params[:id])
    @styles = Style.all
    if @beer.update(beer_params)
      flash[:notice] = "Beer successfully updated!"
      redirect_to profile_path(@user)
    else
      flash[:alert] = "Oops, something went wrong!"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @beer = @user.beers.find(params[:id])
    @beer.destroy
    redirect_to profile_path(@user)
  end

private
  def beer_params
    params.require(:beer).permit(:name, :description, :abv, :container_type, :brew_date, :homebrew, :brewery_name, :user_id, :style_id)
  end

  def require_permission
    if current_user != User.find(params[:user_id])
      flash[:alert] = "Whoops! Only the beer's author can edit or delete a beer."
      redirect_to profile_path(Profile.find(params[:profile_id]))
    end
  end

  def filtering_params(params)
    params.slice(:style_id)
    params.slice(:neighborhood)
  end
end

app/views/beers/_beer.html.erb
<li>
  <div class="row well white-back margin-right beer-tile">
    <h4><span class="bold teal"><%= @beer.name %></span><span class="smaller"> shared by <%= link_to @beer.user.name, profile_path(@beer.user), class: "italic" %></span></h4>
    <p>"<%= @beer.description %>"</p>
    <p><%= @beer.style.name %> from <% if @beer.homebrew %>
    Homebrew
    <% else %>
    <%=@beer.brewery_name %></p>
    <% end %>
    <p>Brewed on: <%= @beer.brew_date %></p>
    <% if current_user %>
      <% if @beer.user_id == current_user.id %>
        <%= link_to 'Edit', edit_user_beer_path(@user, @beer)%><br>
        <%= link_to 'Delete', user_beer_path(@user, @beer), :data => {:confirm => "Are you sure?", :method => "delete"}, remote: true %><br>
      <% else %>
        <h4><%= link_to "Swap!", new_beer_conversation_path(@beer), class: "btn btn-md button-tan" %></h4>
      <% end %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path %> or <%= link_to 'Log In', new_user_session_path %> to swap for this beer!
    <% end %>
  </div>
</li>

app/views/beers/_form.html.erb
<div class="col-xs-12">
  <%= form_for [@user, @beer], html: {id: :new_beer_form}, remote: true do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "% abv (Alcohol by volume)" %>
    <%= f.number_field :abv, :class => 'text_field form-control', :step => 0.1 %>
  </div>
  <div class="form-group">
    <%= f.label :style_id %>
    <%= f.collection_select(:style_id, @styles, :id, :name, {}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <% options = ([['22 oz. bottles', '22 oz. bottles'], ['12 oz. bottles', '12 oz. bottles'], ['Assorted bottles', 'Assorted bottles'], ['Growler', 'Growler'], ['Growlette/Howler', 'Growlette/Howler']]) %>
    <%= f.label :container_type %>
    <%= f.select(:container_type, options_for_select(options), {}, {class: "form-control"})  %>
  </div>
  <div class="form-group">
    <%= f.label :brew_date %>
    <%= f.date_field :brew_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Check here if it's homebrew" %>
    <%= f.check_box :homebrew %>
  </div>
    <div class="form-group">
      <%= f.label "Or if it's from a brewery, which one?" %>
      <%= f.text_field :brewery_name, :class => "form-control" %>
    </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description,  size: "50x4", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, :value => @user.id %>
  </div>
  <h3><%= f.submit 'Submit', :class => "btn btn-lg button-teal"%></h3>
  <% end %><br><br>
</div>

app/views/beers/_small_beer.html.erb
<div class="indent">
  <div class="row well white-back">
    <h4><span class="bold teal"><%= @beer.name %></span><span class="smaller"> shared by <%= link_to @beer.user.name, profile_path(@beer.user), class: "italic" %></span></h4>
    <p>"<%= @beer.description %>"</p>
    <p><%= @beer.style.name %> from <% if @beer.homebrew %>
    Homebrew!
    <% else %>
    <%=@beer.brewery_name %></p>
    <% end %>
    <p>Brewed on: <%= @beer.brew_date %></p>
  </div>
</div>

app/views/beers/create.js.erb
$('#new_beer_form').remove();
$('#new_beer_link').show();
$('#beers').append('<div class="col-sm-6"><%= j render @beer %></div>');
$('#shares').html(<%= @user.beers.count %>)
$('#no_beers_msg').remove();

app/views/beers/edit.html.erb
<div class="container push-down">
  <%= render 'layouts/errors', :object => @beer %>

  <h1 class="center">Edit <%= @beer.name %></h1>

  <div class="col-xs-12">
    <%= form_for [@user, @beer] do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "% abv (Alcohol by volume)" %>
      <%= f.number_field :abv, :class => 'text_field form-control', :step => 0.1 %>
    </div>
    <div class="form-group">
      <%= f.label :style_id %>
      <%= f.collection_select(:style_id, @styles, :id, :name, {}, {class: "form-control"}) %>
    </div>
    <div class="form-group">
      <% options = ([['22 oz. bottles', '22 oz. bottles'], ['12 oz. bottles', '12 oz. bottles'], ['Assorted bottles', 'Assorted bottles'], ['Growler', 'Growler'], ['Growlette/Howler', 'Growlette/Howler']]) %>
      <%= f.label :container_type %>
      <%= f.select(:container_type, options_for_select(options), {}, {class: "form-control"})  %>
    </div>
    <div class="form-group">
      <%= f.label :brew_date %>
      <%= f.date_field :brew_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Check here if it's homebrew" %>
      <%= f.check_box :homebrew %>
    </div>
      <div class="form-group">
        <%= f.label "Or if it's from a brewery, which one?" %>
        <%= f.text_field :brewery_name, :class => "form-control" %>
      </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description,  size: "50x4", :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :user_id, :value => @user.id %>
    </div>
    <%= f.submit 'Submit', :class => "btn btn-lg button-teal"%>
    <% end %><br><br>
  </div>
</div>

app/views/beers/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 push-down">

    <div class="row">
      <div class="col-sm-6 align">
        <h3 class="teal">Search for Beer:</h3>
          <%= form_tag(beers_path, :method => "get", id: "search-form") do %>
          <div class="form-group push-down-lite form-inline">
            <h5><%= label_tag "Find by Style" %>:</h5>
            <%= select_tag :style_id, options_from_collection_for_select(Style.all, :id, :name, params[:style_id]), include_blank: true, class: "form-control", :style => "width:200px" %>
            <%= submit_tag "Search", class: "btn btn-md button-tan" %>
          </div>
          <h5 class="teal">~ OR ~</h5>
          <div class="form-group form-inline push-down-lite">
            <h5><%= label_tag "Find by Neighborhood" %>:</h5>
            <% options = ([['SE Portland', 'SE Portland'], ['N/NE Portland', 'N/NE Portland'], ['SW Portland', 'SW Portland'], ['NW Portland', 'NW Portland']]) %>
            <%= select_tag :neighborhood, options_for_select(options), include_blank: true, class: "form-control", :style => "width:200px" %>
            <%= submit_tag "Search", class: "btn btn-md button-tan" %>
          </div>
          <% end %>
      </div>
      <div class="col-sm-6 map-col">
       <h3 class="blue">Beer is all around you!</h3>
       <div id="map"></div>
       <p class="push-down-lite small">* Privacy is important-we don't share addresses.</p>

      <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(10);
        });
       </script>
     </div>
   </div>

    <div class="row">
      <% if @styled_beers.present? %>
        <h3 class="teal">Search Results:</h3>
          <ul class="no-indent">
            <% @styled_beers.each do |beer| %>
              <div class="col-sm-6">
              <%= render :partial => '/beers/beer', locals: {:@beer => beer, :@user => current_user }%>
              </div>
            <% end %>
          </ul>
      <% elsif @near_beers.present? %>
        <h3 class="teal">Search Results:</h3>
          <ul class="no-indent">
            <% @near_beers.each do |beer| %>
              <div class="col-sm-6">
              <%= render :partial => '/beers/beer', locals: {:@beer => beer, :@user => current_user }%>
              </div>
            <% end %>
          </ul>
      <% else %>
        <% if params[:style_id] %>
        <h4 class="indent">Sorry, nobody's sharing beers like that right now.</h4>
        <% end %>
      <% end %>
    </div>

    <div class="row">
      <h3 class="blue">Recent postings:</h3>
      <ul class="push-down-lite no-indent">
        <% @recent_beers.each do |beer| %>
          <div class="col-sm-6">
          <%= render :partial => '/beers/beer', locals: {:@beer => beer, :@user => current_user }%>
          </div>
        <% end %>
      </ul>
    </div>

    <div class="row push-down-lite bottom">
      <div class="col-sm-6 col-sm-offset-3">
        <% if current_user %>
          <div>
            <h4><%= link_to "Post a beer to share", new_user_beer_path(current_user), remote: true, :class => "btn btn-lg btn-block button-tan", id: "new_beer_link" %></h4>
          </div>
        <% else %>
          <div>
            <h4><%= link_to "Sign-up to share beer", new_user_registration_path, :class => "btn btn-lg btn-block button-tan" %></h4>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/beers/new.html.erb
<%= render 'layouts/errors', :object => @beer %>

<h4 class="center">Post a new beer to share!</h4>

<%= render 'form' %>

app/views/beers/new.js.erb
$('#new_beer_link').hide().after('<%= j render("form") %>');
$('#no_beers_msg').hide();