config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
                controllers: { registrations: "devise/registrations"}

  root :to => 'static_pages#home'

  get "/static_pages/:page" => "static_pages#show"

  resources :posts do
    resources :comments
  end

  resources :profiles

  resources :users do
    resources :beers
  end

  resources :beers do
    resources :conversations
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :messages, only: [:new, :create]

  resources :conversations do
   member do
     post :reply
     post :trash
     post :untrash
   end
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors: </h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beer Swap</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:bold' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("new_swap_logo.png"), root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav">
            <li><%= link_to "Find Beer", beers_path %></li>
            <li class="nav-item"><%= link_to "Blog", posts_path %></li>
            <% if current_user %>
              <li><%= link_to "Inbox", mailbox_inbox_path %></li>
              <li><%= link_to "Profile", profile_path(current_user.id) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => "delete" %></li>
              <li class="round-image-50"><%= image_tag(current_user.profile.avatar.url(:thumb)) %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Signup", new_user_registration_path %></li>
            <% end %>
         </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
      <!-- <div class="flash"> -->

    <div class="container flashing">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> push-down">
          <%= value %>
        </div>
      <% end %>
    </div>

      <!-- </div> -->

        <%= yield %>

      <footer class="footer">
        <div class="text-muted">
          <br><br>&copy; 2016 Molly McGlone
          <br><br><%= link_to "About", "https://www.linkedin.com/in/molly-k-mcglone" %> | <%= link_to "Contact", "https://www.linkedin.com/in/molly-k-mcglone" %>
        </div>
      </footer>
  </body>
</html>